{
 "title": "Pulp Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Pulp Grafana Dashboard\n\n  This is the official dashboard of the Pulp deployment on Operate First.\n  This dashboard has different sections\n  \n  - `Content` -> Pulp content metrics (e.g. how many packages?)\n  - `Operations` -> Pulp operations metrics (e.g. is the component up?)"
   }
  },
  {
   "title": "Content",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pulp's Python packages",
     "type": "stat",
     "description": "Number of packages available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_python_packages_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "New Pulp's Python packages",
     "type": "timeseries",
     "description": "New number of packages available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 5 },
     "targets": [
      {
       "expr": " delta(pulp_python_packages_count{cluster=\"moc/smaug\"}[1d]) ",
       "legendFormat": "Daily new packages"
      },
      {
       "expr": "delta(pulp_python_packages_count{cluster=\"moc/smaug\"}[7d])",
       "legendFormat": "Weekly new packages"
      }
     ]
    },
    {
     "title": "Pulp's Python distributions",
     "type": "stat",
     "description": "Number of distributions available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_python_distributions_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "New Pulp's Python distributions",
     "type": "timeseries",
     "description": "New number of distributions available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
     "targets": [
      {
       "expr": " delta(pulp_python_distributions_count{cluster=\"moc/smaug\"}[1d]) ",
       "legendFormat": "Daily new distributions"
      },
      {
       "expr": "delta(pulp_python_distributions_count{cluster=\"moc/smaug\"}[7d])",
       "legendFormat": "Weekly new distributions"
      }
     ]
    },
    {
     "title": "Pulp's Python publications",
     "type": "stat",
     "description": "Number of publications available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_python_publications_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "New Pulp's Python publications",
     "type": "timeseries",
     "description": "New number of publications available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
     "targets": [
      {
       "expr": " delta(pulp_python_publications_count{cluster=\"moc/smaug\"}[1d]) ",
       "legendFormat": "Daily new publications"
      },
      {
       "expr": "delta(pulp_python_publications_count{cluster=\"moc/smaug\"}[7d])",
       "legendFormat": "Weekly new publications"
      }
     ]
    },
    {
     "title": "Pulp's Python remotes",
     "type": "stat",
     "description": "Number of remotes available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_python_remotes_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "New Pulp's Python remotes",
     "type": "timeseries",
     "description": "New number of remotes available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 29 },
     "targets": [
      {
       "expr": " delta(pulp_python_remotes_count{cluster=\"moc/smaug\"}[1d]) ",
       "legendFormat": "Daily new remotes"
      },
      {
       "expr": "delta(pulp_python_remotes_count{cluster=\"moc/smaug\"}[7d])",
       "legendFormat": "Weekly new remotes"
      }
     ]
    },
    {
     "title": "Pulp's Python repositories",
     "type": "stat",
     "description": "Number of repositories available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_python_repositories_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "New Pulp's Python repositories",
     "type": "timeseries",
     "description": "New number of repositories available in Pulp's Python plugin",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 37 },
     "targets": [
      {
       "expr": " delta(pulp_python_repositories_count{cluster=\"moc/smaug\"}[1d]) ",
       "legendFormat": "Daily new repositories"
      },
      {
       "expr": "delta(pulp_python_repositories_count{cluster=\"moc/smaug\"}[7d])",
       "legendFormat": "Weekly new repositories"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection status to Pulp",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_status_connection{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "Connection status to the database",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_status_database_connection{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "Connection status to Redis",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_status_redis_connection{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "Number of workers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_status_workers_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "Number of tasks",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pulp_tasks_count{cluster=\"moc/smaug\"}"
      }
     ]
    },
    {
     "title": "Number of tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 14 },
     "targets": [
      {
       "expr": "pulp_tasks_count{cluster=\"moc/smaug\"}",
       "legendFormat": "Tasks"
      }
     ]
    }
   ]
  }
 ]
}