#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail

# at least some context
[ -z "$IS_AICOE_CI" ] && echo "Empty"

# Let's ignore the secrets...
PLUGIN_ROOT=$XDG_CONFIG_HOME/kustomize/plugin
mkdir -p $PLUGIN_ROOT/viaduct.ai/v1/ksops/
echo '#!/bin/sh' > $PLUGIN_ROOT/viaduct.ai/v1/ksops/ksops
chmod +x $PLUGIN_ROOT/viaduct.ai/v1/ksops/ksops

# and check all the sub directories with manifests...
k=$(find . -name kustomization.yaml)

for d in $k; do
    echo checking $(dirname $d)
    kustomize build --enable_alpha_plugins $(dirname $d) 2>&1 >/dev/null
done

#end.
