{
 "title": "Thoth Workflow Controllers",
 "tags": [
  "thoth",
  "argo",
  "workflow-controller"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "workflow-controller-metrics-thoth-backend-prod.apps.smaug.na.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.smaug.na.operate-first.cloud, workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.balrog.aws.operate-first.cloud"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "queue_name",
    "query": "cron_wf_queue,pod_queue,wf_cron_queue,workflow_queue"
   },
   { "name": "cluster", "query": "moc/smaug, emea/balrog" }
  ]
 },
 "panels": [
  {
   "title": "General Description",
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Thoth Workflow Controller Grafana Dashboard\n\nThis dashboard contains all metrics focused on the Argo workflow controllers.\n\n## Variables\n\nThe variables you can change are described below. For specific overlays they are clustered togheter and you need to set them all to see all metrics belonging to that overlay.\n\n- *queue_name*: `cron_wf_queue, pod_queue, wf_cron_queue, workflow_queue`\n- *interval*: `1m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 7d`\n\n### moc/smaug\n\n- *cluster*: `moc/smaug`\n- *instance*: `workflow-controller-metrics-thoth-backend-prod.apps.smaug.na.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.smaug.na.operate-first.cloud`\n\n### emea/balrog\n\n- *cluster*: `aws/balrog`\n- *instance*: `workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud, workflow-controller-metrics-thoth-middletier-prod.apps.balrog.aws.operate-first.cloud`"
   }
  },
  {
   "title": "count",
   "type": "graph",
   "description": "A count of all workflows currently accessible by the controller by status",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "error_count",
   "type": "graph",
   "description": "A count of certain errors incurred by the controller",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_error_count{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "queue_adds_count",
   "type": "graph",
   "description": "The number of adds to the queue of workflows or cron workflows",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_adds_count{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "queue_depth_count",
   "type": "graph",
   "description": "The depth of the queue of workflows or cron workflows to be processed by the controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Workflow queue latency [%]",
   "type": "graph",
   "description": "Percentage of workflows that has queue latency below a certain threshold",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_latency_bucket{field=\"$instance\", cluster=\"$cluster\", queue_name=\"$queue_name\"} / ignoring(le) group_left argo_workflows_queue_latency_count{field=\"$instance\", cluster=\"$cluster\", queue_name=\"$queue_name\"}",
     "legendFormat": "queue_latency: {{le}}"
    }
   ]
  },
  {
   "title": "operation_duration_seconds",
   "type": "bargauge",
   "description": "A histogram of durations of operations",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_operation_duration_seconds_bucket{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Allocated Go Bytes",
   "type": "graph",
   "description": "Total number of bytes currently allocated in go",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{field=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "Allocated Bytes"
    }
   ]
  }
 ]
}