{
 "title": "Thoth Service metrics",
 "tags": [
  "thoth",
  "service-metrics",
  "metrics-exporter",
  "dependencies-components"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "moc/smaug" }
  ]
 },
 "panels": [
  {
   "title": "General Description",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Thoth service metrics Grafana Dashboard\n\nThis dashboard contains all metrics focused on component overview (e.g. version of libraries used and thoth-storages library for alembic version deployed)\n\n## Variables\n\nThe variables you can change are described below. For specific overlays they are clustered togheter and you need to set them all to see all metrics belonging to that overlay.\n\n### moc/smaug\n\n- *cluster*: `moc/smaug`\n"
   }
  },
  {
   "title": "Thoth Components Versions",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_api_info{cluster=\"$cluster\"}",
     "legendFormat": "SERVICE: {{service}} | VERSION: {{version}}"
    },
    {
     "expr": "thoth_metrics_exporter_info{cluster=\"$cluster\"}",
     "legendFormat": "SERVICE: {{service}} | VERSION: {{version}}"
    },
    {
     "expr": "management_api_info{cluster=\"$cluster\"}",
     "legendFormat": "SERVICE: {{service}} | VERSION: {{version}}"
    },
    {
     "expr": "thoth_investigator_consumer_info{cluster=\"$cluster\"}",
     "legendFormat": "SERVICE:  {{service}} | VERSION: {{version}}"
    }
   ]
  },
  {
   "title": "Thoth Components Versions (cronjobs)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_package_release_job_info{cluster=\"$cluster\"}",
     "legendFormat": "{{exported_job}}  | VERSION: {{version}} "
    },
    {
     "expr": "thoth_graph_refresh_job_info{cluster=\"$cluster\"}",
     "legendFormat": "{{exported_job}}  | VERSION: {{version}} "
    }
   ]
  },
  {
   "title": "Database alembic version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_database_schema_revision_table{cluster=\"$cluster\"} == 1",
     "legendFormat": "{{revision}} "
    }
   ]
  },
  {
   "title": "Database Schema revision for Thoth components",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_database_schema_revision_script{cluster=\"$cluster\"} == 1",
     "legendFormat": "COMPONENT: {{component}} alembic version: {{revision}}"
    }
   ]
  },
  {
   "title": "Is component schema == database schema? [0 yes, 1 no -> alarm]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graph_db_component_revision_check{cluster=\"$cluster\"}",
     "legendFormat": "COMPONENT: {{component}} | DEPLOYMENT: {{env}}"
    }
   ]
  }
 ]
}