{
 "title": "Thoth Service metrics user-api",
 "tags": [
  "thoth",
  "service-metrics",
  "user-api"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "user-api-thoth-frontend-prod.apps.smaug.na.operate-first.cloud, user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud"
   }
  ]
 },
 "panels": [
  {
   "title": "General Description",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Thoth User API Metrics\n\nThis dashboard contains all metrics regarding Thoth User API.\n\n## Variables\n\nThe variables you can change are described below. For specific overlays they are clustered togheter and you need to set them all to see all metrics belonging to that overlay.\n\n### moc/smaug\n\n- *instance*: `user-api-thoth-frontend-prod.apps.smaug.na.operate-first.cloud`\n\n### emea/balrog\n\n- *instance*: `user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud`\n           "
   }
  },
  {
   "title": "Total requests per minute [TH-GP-0023]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{field=\"$instance\", method=\"GET\"}[$interval])",
     "legendFormat": "GET: HTTP {{ status }}"
    },
    {
     "expr": "increase(flask_http_request_total{field=\"$instance\", method=\"POST\"}[$interval])",
     "legendFormat": "POST: HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Percentage of endpoint hit (GET, 200) [TH-GP-0033]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\",  method=\"GET\", status=\"200\"} / ignoring(exported_endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"GET\", status=\"200\"}",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Percentage of endpoint hit (POST, [200, 202]) [TH-GP-0033]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\", method=\"POST\", status=\"202\"} / ignoring(exported_endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"POST\", status=\"202\"}",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    },
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\", method=\"POST\", status=\"200\"} / ignoring(exported_endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"POST\", status=\"200\"}",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Errors per second [TH-GP-0026]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{field=\"$instance\", status!=\"200\"}[$interval]))",
     "legendFormat": "errors "
    }
   ]
  },
  {
   "title": "Memory usage [TH-GP-0024]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{field=\"$instance\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU usage [TH-GP-0025]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{field=\"$instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Average response time [30s] [TH-GP-0028]",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])\n/\nrate(flask_http_request_duration_seconds_count{field=\"$instance\",endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms [TH-GP-0029]",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"/api/v1./api/v1_swagger_ui_index\", le=\"0.25\", status=~\"200|202\"}[$interval]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Request duration - p50 [TH-GP-0030]",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\",endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\",  status=~\"200|202\"}[60s]))",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Request duration - p90 [TH-GP-0031]",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\",endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", endpoint!=\"/api/v1./api/v1_swagger_ui_static\", status=~\"200|202\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Requests per second  [TH-GP-0026] (all endpoints)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Average response time  [TH-GP-0028] (All endpoints)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])\n/\nrate(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms [TH-GP-0029] (All endpoints)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\", le=\"0.25\"}[$interval]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Request duration - p50 [TH-GP-0030] (All endpoints)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  },
  {
   "title": "Request duration - p90 [TH-GP-0031] (All endpoint)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{exported_endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}