{
 "title": "Total requests per minute [TH-GP-0023]",
 "panels": [
  {
   "title": "Total requests per minute [TH-GP-0023]",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{field=\"$instance\", method=\"GET\"}[$interval])",
     "legendFormat": "GET: HTTP {{ status }}"
    },
    {
     "expr": "increase(flask_http_request_total{field=\"$instance\", method=\"POST\"}[$interval])",
     "legendFormat": "POST: HTTP {{ status }}"
    }
   ]
  }
 ]
}
{
 "title": "Percentage of endpoints hit (GET, 200) [TH-GP-0033]",
 "panels": [
  {
   "title": "Percentage of endpoint hit (GET, 200) [TH-GP-0033]",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\",  method=\"GET\", status=\"200\"} / ignoring(endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"GET\", status=\"200\"}",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Percentage of endpoints hit (POST, 200, 202) [TH-GP-0033]",
 "panels": [
  {
   "title": "Percentage of endpoint hit (POST, [200, 202]) [TH-GP-0033]",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\", method=\"POST\", status=\"202\"} / ignoring(endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"POST\", status=\"202\"}",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    },
    {
     "expr": "flask_http_request_duration_seconds_count{field=\"$instance\", method=\"POST\", status=\"200\"} / ignoring(endpoint) group_left flask_http_request_total{field=\"$instance\", method=\"POST\", status=\"200\"}",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Errors per second [TH-GP-0026]",
 "panels": [
  {
   "title": "Errors per second [TH-GP-0026]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{field=\"$instance\", status!=\"200\"}[$interval]))",
     "legendFormat": "errors "
    }
   ]
  }
 ]
}
{
 "title": "Memory usage [TH-GP-0024] and CPU usage [TH-GP-0025]",
 "panels": [
  {
   "title": "Memory usage [TH-GP-0024]",
   "type": "graph",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{field=\"$instance\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage [TH-GP-0025]",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{field=\"$instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}
{
 "title": "Average response time [1m] [TH-GP-0028]",
 "panels": [
  {
   "title": "Average response time [30s] [TH-GP-0028]",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])\n/\nrate(flask_http_request_duration_seconds_count{field=\"$instance\",endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Requests under 250ms [TH-GP-0029]",
 "panels": [
  {
   "title": "Requests under 250ms [TH-GP-0029]",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"/api/v1./api/v1_swagger_ui_index\", le=\"0.25\", status=~\"200|202\"}[$interval]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\", endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", status=~\"200|202\"}[$interval])",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Request duration - p50 [TH-GP-0030]",
 "panels": [
  {
   "title": "Request duration - p50 [TH-GP-0030]",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\",endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\",endpoint!=\"/api/v1./api/v1_swagger_ui_static\",  status=~\"200|202\"}[60s]))",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Request duration - p90 [TH-GP-0031]",
 "panels": [
  {
   "title": "Request duration - p90 [TH-GP-0031]",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\",endpoint!=\"/api/v1./api/v1_openapi_json\", endpoint!=\"None\", endpoint!=\"base_url\", endpoint!=\"api_v1\", endpoint!=\"api_readiness\",endpoint!=\"api_liveness\",endpoint!=\"/api/v1./api/v1_swagger_ui_index\", endpoint!=\"/api/v1./api/v1_swagger_ui_static\", status=~\"200|202\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Requests per second [TH-GP-0026]",
 "panels": [
  {
   "title": "Requests per second  [TH-GP-0026] (all endpoints)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Average response time  [TH-GP-0028]",
 "panels": [
  {
   "title": "Average response time  [TH-GP-0028] (All endpoints)",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])\n/\nrate(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Requests under 250ms [TH-GP-0029]",
 "panels": [
  {
   "title": "Requests under 250ms [TH-GP-0029] (All endpoints)",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\", le=\"0.25\"}[$interval]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval])",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Request duration - p50 [TH-GP-0030]",
 "panels": [
  {
   "title": "Request duration - p50 [TH-GP-0030] (All endpoints)",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Request duration - p90 [TH-GP-0031]",
 "panels": [
  {
   "title": "Request duration - p90 [TH-GP-0031] (All endpoint)",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{field=\"$instance\", endpoint!=\"api_v1\", endpoint!=\"base_url\", status=\"200\"}[$interval]))",
     "legendFormat": "ENDPOINT: {{endpoint}} | METHOD: {{method}} | STATUS : {{status}}"
    }
   ]
  }
 ]
}