{
 "title": "Thoth Knowledge Graph content metrics",
 "tags": [
  "thoth",
  "knowledge graph"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "metrics-exporter-thoth-infra-prod.apps.balrog.aws.operate-first.cloud,open.cloud"
   }
  ]
 },
 "panels": [
  {
   "title": "Thoth Integrations",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_adviser_count_per_source_type{field=\"$instance\"}",
     "legendFormat": "{{thoth_integration}}"
    }
   ]
  },
  {
   "title": "Thoth Integrations",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thoth_graphdb_adviser_count_per_source_type{field=\"$instance\", cluster=\"emea/balrog\"}",
     "legendFormat": "{{thoth_integration}}"
    }
   ]
  },
  {
   "title": "GitHub repos with Kebechet active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "thoth_kebechet_total_active_repo_count{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "GitHub repos with Kebechet active",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thoth_kebechet_total_active_repo_count{field=\"$instance\", cluster=\"emea/balrog\"}",
     "legendFormat": "Kebechet Installations"
    }
   ]
  },
  {
   "title": "Python Packages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_pypi_stats{stats_type=\"packages\", field=\"$instance\"}",
     "legendFormat": "PyPI"
    },
    {
     "expr": "sum(thoth_graphdb_total_python_packages_per_indexes{field=\"$instance\"})",
     "legendFormat": "Thoth"
    }
   ]
  },
  {
   "title": "Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_pypi_stats{stats_type=\"releases\", field=\"$instance\"}",
     "legendFormat": "PyPI"
    },
    {
     "expr": "thoth_graphdb_number_python_package_versions{field=\"$instance\"}",
     "legendFormat": "Thoth"
    }
   ]
  },
  {
   "title": "Thoth Python Packages respect to PyPI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_python_packages_per_indexes{field=\"$instance\", index_url=\"https://pypi.org/simple\"} / ignoring(index_url, stats_type) group_right thoth_pypi_stats{stats_type=\"packages\", field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thoth Python Packages Releases respect to PyPI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_number_python_package_versions{field=\"$instance\"} / ignoring(stats_type) group_right thoth_pypi_stats{stats_type=\"releases\", field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thoth registered indexes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_python_indexes{field=\"$instance\"}"
    }
   ]
  },
  { "title": "Solvers Knowledge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Solvers (ConfigMap)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solvers{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solvers (From Database)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solvers_database{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases rhel-8-py38",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solved_python_packages{field=\"$instance\", solver_name=\"solver-rhel-8-py38\"} / ignoring(solver_name) group_left thoth_graphdb_number_python_package_versions{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases rhel-8-py38",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solved_python_packages{field=\"$instance\", solver_name=\"solver-rhel-8-py38\", cluster=\"emea/balrog\"} / ignoring(solver_name) group_left thoth_graphdb_number_python_package_versions{field=\"$instance\", cluster=\"emea/balrog\"}",
     "legendFormat": "Solved Python Packages rhel-8-py38"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases solver-fedora-34-py39",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solved_python_packages{field=\"$instance\", solver_name=\"solver-fedora-34-py39\"} / ignoring(solver_name) group_left thoth_graphdb_number_python_package_versions{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases solver-fedora-34-py39",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solved_python_packages{field=\"$instance\", solver_name=\"solver-fedora-34-py39\", cluster=\"emea/balrog\"} / ignoring(solver_name) group_left thoth_graphdb_number_python_package_versions{field=\"$instance\", cluster=\"emea/balrog\"}",
     "legendFormat": "Solved Python Packages Fedora-34-py39"
    }
   ]
  },
  {
   "title": "Unsolved Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_unsolved_python_packages{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_number_solved_python_packages{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases no error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_python_packages_with_no_error{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases with error (general)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_python_packages_with_solver_error{field=\"$instance\"}) - sum(thoth_graphdb_total_python_packages_with_solver_error_unsolvable{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases (unsolvable)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_python_packages_with_solver_error_unsolvable{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases no error [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_python_packages_with_no_error{field=\"$instance\"}) / sum(thoth_graphdb_total_number_solved_python_packages{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases with error (general) [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thoth_graphdb_total_python_packages_with_solver_error{field=\"$instance\"}) - sum(thoth_graphdb_total_python_packages_with_solver_error_unsolvable{field=\"$instance\"})) / sum(thoth_graphdb_total_number_solved_python_packages{field=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Solved Python Packages Releases with error (unsolvable) [%]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thoth_graphdb_total_python_packages_with_solver_error_unsolvable{field=\"$instance\"}) / sum(thoth_graphdb_total_number_solved_python_packages{field=\"$instance\"})"
    }
   ]
  },
  { "title": "Security Knowledge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Number of CVE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_cve{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SI Unanalyzed Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_unanalyzed_python_packages{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SI Analyzed Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_analyzed_python_packages{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SI Not Analyzable Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_not_analyzable_python_packages{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SI Analyzed Python Packages Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_analyzed_python_packages{field=\"$instance\"} / thoth_graphdb_number_python_package_versions{field=\"$instance\"}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Python Packages per Indexes [TH-GPC-005]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_python_packages_per_indexes{field=\"$instance\"}",
     "legendFormat": "PythonPackages: {{index_url}}"
    },
    {
     "expr": "thoth_graphdb_sum_python_packages_per_indexes{field=\"$instance\"}",
     "legendFormat": "Tot Python Packages per Index"
    },
    {
     "expr": "thoth_graphdb_number_python_package_versions{field=\"$instance\"}",
     "legendFormat": "Tot Python Packages Releases"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Unsolved Python Packages per solver [TH-GPC-027]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_unsolved_python_packages_per_solver{field=\"$instance\"}",
     "legendFormat": "Unsolved Python Packages per: {{solver_name}}"
    }
   ]
  },
  {
   "title": "Solved Python Packages per solver [TH-GPC-027]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_solved_python_packages{field=\"$instance\"}",
     "legendFormat": "Solved Python Packages Releases per: {{solver_name}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Info about Solved Python Packages for all Solvers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_python_packages_with_no_error{field=\"$instance\"}",
     "legendFormat": "Solved Python Packages with no error: {{solver_name}}"
    }
   ]
  },
  {
   "title": "Info about Solved Python Packages for all Solvers with errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_python_packages_with_solver_error{field=\"$instance\"}",
     "legendFormat": "Solved Python Packages with solver error (unsolvable=False, unparseable=False)): {{solver_name}}"
    },
    {
     "expr": "thoth_graphdb_total_python_packages_with_solver_error_unsolvable{field=\"$instance\"}",
     "legendFormat": "Solved Python Packages with solver error (unsolvable=TRUE): {{solver_name}}"
    },
    {
     "expr": "thoth_graphdb_total_python_packages_with_solver_error_unparseable{field=\"$instance\"}",
     "legendFormat": "Solved Python Packages with solver error (unparseable=TRUE): {{solver_name}}"
    }
   ]
  },
  { "title": "Python Packages Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "SI Unanalzyed Python Packages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_unanalyzed_python_packages{field=\"$instance\"}",
     "legendFormat": "SI Unanalyzed Python Packages"
    }
   ]
  },
  {
   "title": "SI Analyzed Python Packages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_si_analyzed_python_packages{field=\"$instance\"}",
     "legendFormat": "SI Analyzed Python Packages"
    }
   ]
  },
  { "title": "Performance Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "PI Information [TH-GPC-009]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_number_of_pi_per_framework{field=\"$instance\"}",
     "legendFormat": "FRAMEWORK: {{framework}} | PI: {{pi}}"
    }
   ]
  },
  {
   "title": "Number of Performance Indicators [TH-GPC-010]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_performance_records{field=\"$instance\"}",
     "legendFormat": "{{performance_table}}"
    }
   ]
  },
  { "title": "PI Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "matmul Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_performance_records{field=\"$instance\", performance_table=\"pi_matmul\"}"
    }
   ]
  },
  {
   "title": "conv2d Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_performance_records{field=\"$instance\", performance_table=\"pi_conv2d\"}"
    }
   ]
  },
  {
   "title": "conv1d Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_performance_records{field=\"$instance\", performance_table=\"pi_conv1d\"}"
    }
   ]
  },
  {
   "title": "pybench Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_total_performance_records{field=\"$instance\", performance_table=\"pi_pybench\"}"
    }
   ]
  },
  { "title": "Users Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "User Information [TH-GPC-011]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_user_software_stacks_records{field=\"$instance\"}",
     "legendFormat": "External (User) Software Stacks"
    },
    {
     "expr": "thoth_graphdb_total_user_run_software_environment{field=\"$instance\"}",
     "legendFormat": "Number of External Software Environment for Run"
    },
    {
     "expr": "thoth_graphdb_total_main_records{field=\"$instance\", main_table=~\"external_.*\"}",
     "legendFormat": "Number of {{main_table}}"
    }
   ]
  },
  {
   "title": "Software Environment (Build and Run) and Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 }
  },
  {
   "title": "SoftwareEnvironment Information [TH-GPC-012]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_total_run_software_environment{field=\"$instance\"}",
     "legendFormat": "Number of Software Environment for Run"
    },
    {
     "expr": "thoth_graphdb_total_build_software_environment{field=\"$instance\"}",
     "legendFormat": "Number of Software Environment for Build"
    }
   ]
  },
  {
   "title": "Python software stacks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_advised_software_stacks_records{field=\"$instance\"}",
     "legendFormat": "Number of advised software stacks"
    },
    {
     "expr": "thoth_graphdb_user_software_stacks_records{field=\"$instance\"}",
     "legendFormat": "Number of user software stacks"
    }
   ]
  }
 ]
}