{
 "title": "Thoth PostgreSQL metrics",
 "tags": [
  "thoth",
  "ops-metrics",
  "postgresql-metrics-exporter",
  "balrog-prod"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "postgres-metrics-exporter-thoth-graph-prod.apps.balrog.aws.operate-first.cloud/"
   },
   {
    "name": "metrics_exporter_instance",
    "query": "metrics-exporter-thoth-infra-prod.apps.balrog.aws.operate-first.cloud"
   },
   { "name": "env", "query": "emea/balrog" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "description": "PostgreSQL version",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{field=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Sets the maximum number of concurrent connections.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Sets the number of shared memory buffers used by the server. [Units converted to bytes.]",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "description": "Sets the planner’s assumption about the size of the data cache. [Units converted to bytes.]",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "description": "Sets the maximum memory to be used for maintenance operations. [Units converted to bytes.]",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "description": "Sets the maximum memory to be used for query workspaces. [Units converted to bytes.]",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "description": "Sets the WAL size that triggers a checkpoint. [Units converted to bytes.]",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "description": "Sets the planner’s estimate of the cost of a nonsequentially fetched disk page.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "description": "Sets the planner’s estimate of the cost of a sequentially fetched disk page.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "description": "Maximum number of concurrent worker processes.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "description": "Sets the maximum number of parallel processes per executor node.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers_per_gather{field=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "INSERT"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{field=\"$instance\", datname=\"postgres\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{field=\"$instance\", datname=\"postgres\"}",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{field=\"$instance\", datname=\"postgres\"}[5m])",
     "legendFormat": "SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{field=\"$instance\", datname=\"thoth\"} / (pg_stat_database_blks_read{field=\"$instance\", datname=\"thoth\"} + pg_stat_database_blks_hit{field=\"$instance\", datname=\"thoth\"})",
     "legendFormat": "Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "description": "Number of locks",
   "gridPos": { "h": 12, "w": 10, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{field=\"$instance\", datname=\"thoth\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{field=\"$instance\", datname=\"thoth\"}[5m])",
     "legendFormat": "Temp Bytes"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "description": "pg_stat_bgwriter_buffers_alloc (cumulative)\nNumber of buffers allocated, \n\npg_stat_bgwriter_buffers_backend (cumulative)\nNumber of buffers written directly by a backend, \n\npg_stat_bgwriter_buffers_backend_fsync (cumulative)\nNumber of times a backend had to execute its own fsync call (normally the background writer handles those even when the backend does its own write),\n\npg_stat_bgwriter_buffers_checkpoint (cumulative)\nNumber of buffers written during checkpoints,\n\npg_stat_bgwriter_buffers_clean (cumulative)\nNumber of buffers written by the background writer",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{field=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{field=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{field=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{field=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{field=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "description": "pg_stat_bgwriter_checkpoint_sync_time (cumulative)\nTotal amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk, in milliseconds,\n\npg_stat_bgwriter_checkpoint_write_time (cumulative)\nTotal amount of time that has been spent in the portion of checkpoint processing where files are written to disk, in milliseconds",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{field=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{field=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  {
   "title": "Table Bloat data (pct)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_pct_bloat_data_table{env=\"$env\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Table Bloat data (mb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_mb_bloat_data_table{env=\"$env\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Index Bloat data (pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_pct_index_bloat_data_table{env=\"$env\"}",
     "legendFormat": "{{table_name}}: {{index_name}}"
    }
   ]
  },
  {
   "title": "Index Bloat data (mb)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_mb_index_bloat_data_table{env=\"$env\"}",
     "legendFormat": "{{table_name}}: {{index_name}}"
    }
   ]
  },
  {
   "title": "Schema corruption (amcheck) [no 0, yes 1 -> alarm]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_is_corrupted{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Database connection issue [no 0, yes 1,  -> alarm]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thoth_graphdb_connection_issues{field=\"$metrics_exporter_instance\"}"
    }
   ]
  },
  {
   "title": "Thoth Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "thoth_graphdb_size{field=\"$metrics_exporter_instance\"}",
     "legendFormat": "Thoth Database Size"
    }
   ]
  }
 ]
}